// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type App struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dir                  string   `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	Program              string   `protobuf:"bytes,3,opt,name=program,proto3" json:"program,omitempty"`
	Args                 string   `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	StdOut               string   `protobuf:"bytes,5,opt,name=std_out,json=stdOut,proto3" json:"std_out,omitempty"`
	StdErr               string   `protobuf:"bytes,6,opt,name=std_err,json=stdErr,proto3" json:"std_err,omitempty"`
	AutoRestart          bool     `protobuf:"varint,7,opt,name=auto_restart,json=autoRestart,proto3" json:"auto_restart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *App) GetProgram() string {
	if m != nil {
		return m.Program
	}
	return ""
}

func (m *App) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *App) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

func (m *App) GetStdErr() string {
	if m != nil {
		return m.StdErr
	}
	return ""
}

func (m *App) GetAutoRestart() bool {
	if m != nil {
		return m.AutoRestart
	}
	return false
}

type AppNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppNameRequest) Reset()         { *m = AppNameRequest{} }
func (m *AppNameRequest) String() string { return proto.CompactTextString(m) }
func (*AppNameRequest) ProtoMessage()    {}
func (*AppNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *AppNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppNameRequest.Unmarshal(m, b)
}
func (m *AppNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppNameRequest.Marshal(b, m, deterministic)
}
func (m *AppNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppNameRequest.Merge(m, src)
}
func (m *AppNameRequest) XXX_Size() int {
	return xxx_messageInfo_AppNameRequest.Size(m)
}
func (m *AppNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppNameRequest proto.InternalMessageInfo

func (m *AppNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AppResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	App                  *App     `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppResponse) Reset()         { *m = AppResponse{} }
func (m *AppResponse) String() string { return proto.CompactTextString(m) }
func (*AppResponse) ProtoMessage()    {}
func (*AppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *AppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppResponse.Unmarshal(m, b)
}
func (m *AppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppResponse.Marshal(b, m, deterministic)
}
func (m *AppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppResponse.Merge(m, src)
}
func (m *AppResponse) XXX_Size() int {
	return xxx_messageInfo_AppResponse.Size(m)
}
func (m *AppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppResponse proto.InternalMessageInfo

func (m *AppResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AppResponse) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type AppListResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Apps                 []*App   `protobuf:"bytes,2,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppListResponse) Reset()         { *m = AppListResponse{} }
func (m *AppListResponse) String() string { return proto.CompactTextString(m) }
func (*AppListResponse) ProtoMessage()    {}
func (*AppListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{3}
}

func (m *AppListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppListResponse.Unmarshal(m, b)
}
func (m *AppListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppListResponse.Marshal(b, m, deterministic)
}
func (m *AppListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppListResponse.Merge(m, src)
}
func (m *AppListResponse) XXX_Size() int {
	return xxx_messageInfo_AppListResponse.Size(m)
}
func (m *AppListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppListResponse proto.InternalMessageInfo

func (m *AppListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AppListResponse) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

func init() {
	proto.RegisterType((*App)(nil), "App")
	proto.RegisterType((*AppNameRequest)(nil), "AppNameRequest")
	proto.RegisterType((*AppResponse)(nil), "AppResponse")
	proto.RegisterType((*AppListResponse)(nil), "AppListResponse")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x6b, 0x2a, 0x31,
	0x14, 0x85, 0x1d, 0x33, 0x33, 0x3e, 0xaf, 0xf2, 0x94, 0x2c, 0xde, 0x0b, 0xd3, 0x8d, 0x1d, 0x8a,
	0xb8, 0xca, 0xc2, 0xae, 0xba, 0x2a, 0x53, 0x10, 0x37, 0xa5, 0x85, 0x40, 0x37, 0xdd, 0x48, 0x34,
	0x41, 0x5c, 0x8c, 0xb9, 0x4d, 0x32, 0x85, 0xfe, 0xa9, 0x2e, 0xfa, 0x0b, 0x4b, 0x32, 0x28, 0xb6,
	0x95, 0xee, 0xce, 0x7c, 0xe7, 0x9c, 0x7b, 0xe7, 0x42, 0xa0, 0x2f, 0x11, 0x39, 0x5a, 0xe3, 0x4d,
	0x01, 0x6b, 0xe9, 0x74, 0xab, 0xcb, 0xf7, 0x04, 0x48, 0x85, 0x48, 0x29, 0xa4, 0x7b, 0x59, 0x6b,
	0x96, 0x4c, 0x92, 0x59, 0x5f, 0x44, 0x4d, 0xc7, 0x40, 0xd4, 0xce, 0xb2, 0x6e, 0x44, 0x41, 0x52,
	0x06, 0x3d, 0xb4, 0x66, 0x6b, 0x65, 0xcd, 0x48, 0xa4, 0x87, 0xcf, 0xd0, 0x97, 0x76, 0xeb, 0x58,
	0xda, 0xf6, 0x83, 0xa6, 0xff, 0xa1, 0xe7, 0xbc, 0x5a, 0x99, 0xc6, 0xb3, 0x2c, 0xe2, 0xdc, 0x79,
	0xf5, 0xd8, 0xf8, 0x83, 0xa1, 0xad, 0x65, 0xf9, 0xd1, 0x58, 0x58, 0x4b, 0x2f, 0x61, 0x28, 0x1b,
	0x6f, 0x56, 0x56, 0x3b, 0x2f, 0xad, 0x67, 0xbd, 0x49, 0x32, 0xfb, 0x23, 0x06, 0x81, 0x89, 0x16,
	0x95, 0x57, 0xf0, 0xb7, 0x42, 0x7c, 0x90, 0xb5, 0x16, 0xfa, 0xa5, 0xd1, 0xce, 0x9f, 0xfb, 0xf5,
	0xf2, 0x06, 0x06, 0x15, 0xa2, 0xd0, 0x0e, 0xcd, 0xde, 0xe9, 0x10, 0xd9, 0x18, 0xd5, 0x46, 0x32,
	0x11, 0x35, 0xfd, 0x07, 0x44, 0x22, 0xc6, 0xeb, 0x06, 0xf3, 0x94, 0x87, 0x78, 0x00, 0xe5, 0x2d,
	0x8c, 0x2a, 0xc4, 0xfb, 0x9d, 0xf3, 0xbf, 0xd6, 0x19, 0xa4, 0x12, 0xd1, 0xb1, 0xee, 0x84, 0x1c,
	0xfb, 0x91, 0xcc, 0x3f, 0x12, 0xc8, 0x96, 0x8d, 0xb4, 0x8a, 0x96, 0x90, 0x86, 0x39, 0x34, 0xe7,
	0x8b, 0x1a, 0xfd, 0x5b, 0x31, 0xe6, 0xdf, 0x26, 0x97, 0x1d, 0x3a, 0x05, 0xb2, 0xd4, 0x9e, 0x8e,
	0xf8, 0xd7, 0xab, 0x8a, 0x21, 0x3f, 0x39, 0xa0, 0xec, 0x50, 0x06, 0xa4, 0x52, 0x8a, 0xc6, 0x45,
	0x45, 0x9f, 0x9f, 0x38, 0x17, 0x90, 0x3f, 0xa1, 0x92, 0x5e, 0x9f, 0x33, 0xa7, 0x90, 0x0b, 0x5d,
	0x9b, 0x57, 0xfd, 0x73, 0xc3, 0x69, 0xee, 0x2e, 0x7b, 0x26, 0x16, 0x37, 0xeb, 0x3c, 0xbe, 0x8a,
	0xeb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0x7b, 0x41, 0x64, 0x2e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GuardClient is the client API for Guard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GuardClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AppListResponse, error)
	Get(ctx context.Context, in *AppNameRequest, opts ...grpc.CallOption) (*AppResponse, error)
	Add(ctx context.Context, in *App, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *App, opts ...grpc.CallOption) (*Response, error)
	Remove(ctx context.Context, in *AppNameRequest, opts ...grpc.CallOption) (*Response, error)
}

type guardClient struct {
	cc *grpc.ClientConn
}

func NewGuardClient(cc *grpc.ClientConn) GuardClient {
	return &guardClient{cc}
}

func (c *guardClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	err := c.cc.Invoke(ctx, "/Guard/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardClient) Get(ctx context.Context, in *AppNameRequest, opts ...grpc.CallOption) (*AppResponse, error) {
	out := new(AppResponse)
	err := c.cc.Invoke(ctx, "/Guard/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardClient) Add(ctx context.Context, in *App, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Guard/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardClient) Update(ctx context.Context, in *App, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Guard/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guardClient) Remove(ctx context.Context, in *AppNameRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Guard/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuardServer is the server API for Guard service.
type GuardServer interface {
	List(context.Context, *Empty) (*AppListResponse, error)
	Get(context.Context, *AppNameRequest) (*AppResponse, error)
	Add(context.Context, *App) (*Response, error)
	Update(context.Context, *App) (*Response, error)
	Remove(context.Context, *AppNameRequest) (*Response, error)
}

// UnimplementedGuardServer can be embedded to have forward compatible implementations.
type UnimplementedGuardServer struct {
}

func (*UnimplementedGuardServer) List(ctx context.Context, req *Empty) (*AppListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedGuardServer) Get(ctx context.Context, req *AppNameRequest) (*AppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedGuardServer) Add(ctx context.Context, req *App) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedGuardServer) Update(ctx context.Context, req *App) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedGuardServer) Remove(ctx context.Context, req *AppNameRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}

func RegisterGuardServer(s *grpc.Server, srv GuardServer) {
	s.RegisterService(&_Guard_serviceDesc, srv)
}

func _Guard_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Guard/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guard_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Guard/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardServer).Get(ctx, req.(*AppNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guard_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Guard/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardServer).Add(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guard_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Guard/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardServer).Update(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guard_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Guard/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardServer).Remove(ctx, req.(*AppNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Guard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Guard",
	HandlerType: (*GuardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Guard_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Guard_Get_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Guard_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Guard_Update_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Guard_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}
