// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Dir                  string   `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
	Program              string   `protobuf:"bytes,4,opt,name=program,proto3" json:"program,omitempty"`
	Args                 string   `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	StdOut               string   `protobuf:"bytes,6,opt,name=std_out,json=stdOut,proto3" json:"std_out,omitempty"`
	StdErr               string   `protobuf:"bytes,7,opt,name=std_err,json=stdErr,proto3" json:"std_err,omitempty"`
	Spec                 string   `protobuf:"bytes,8,opt,name=spec,proto3" json:"spec,omitempty"`
	Timeout              int64    `protobuf:"varint,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
	IsMonitor            bool     `protobuf:"varint,10,opt,name=is_monitor,json=isMonitor,proto3" json:"is_monitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *Job) GetProgram() string {
	if m != nil {
		return m.Program
	}
	return ""
}

func (m *Job) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *Job) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

func (m *Job) GetStdErr() string {
	if m != nil {
		return m.StdErr
	}
	return ""
}

func (m *Job) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *Job) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Job) GetIsMonitor() bool {
	if m != nil {
		return m.IsMonitor
	}
	return false
}

type JobNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobNameRequest) Reset()         { *m = JobNameRequest{} }
func (m *JobNameRequest) String() string { return proto.CompactTextString(m) }
func (*JobNameRequest) ProtoMessage()    {}
func (*JobNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *JobNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobNameRequest.Unmarshal(m, b)
}
func (m *JobNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobNameRequest.Marshal(b, m, deterministic)
}
func (m *JobNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobNameRequest.Merge(m, src)
}
func (m *JobNameRequest) XXX_Size() int {
	return xxx_messageInfo_JobNameRequest.Size(m)
}
func (m *JobNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobNameRequest proto.InternalMessageInfo

func (m *JobNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type JobResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Job                  *Job     `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResponse) Reset()         { *m = JobResponse{} }
func (m *JobResponse) String() string { return proto.CompactTextString(m) }
func (*JobResponse) ProtoMessage()    {}
func (*JobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{2}
}

func (m *JobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResponse.Unmarshal(m, b)
}
func (m *JobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResponse.Marshal(b, m, deterministic)
}
func (m *JobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResponse.Merge(m, src)
}
func (m *JobResponse) XXX_Size() int {
	return xxx_messageInfo_JobResponse.Size(m)
}
func (m *JobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobResponse proto.InternalMessageInfo

func (m *JobResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *JobResponse) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type JobListResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Jobs                 []*Job   `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobListResponse) Reset()         { *m = JobListResponse{} }
func (m *JobListResponse) String() string { return proto.CompactTextString(m) }
func (*JobListResponse) ProtoMessage()    {}
func (*JobListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{3}
}

func (m *JobListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobListResponse.Unmarshal(m, b)
}
func (m *JobListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobListResponse.Marshal(b, m, deterministic)
}
func (m *JobListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobListResponse.Merge(m, src)
}
func (m *JobListResponse) XXX_Size() int {
	return xxx_messageInfo_JobListResponse.Size(m)
}
func (m *JobListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobListResponse proto.InternalMessageInfo

func (m *JobListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *JobListResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterType((*JobNameRequest)(nil), "JobNameRequest")
	proto.RegisterType((*JobResponse)(nil), "JobResponse")
	proto.RegisterType((*JobListResponse)(nil), "JobListResponse")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4f, 0x6b, 0xdb, 0x30,
	0x14, 0x8f, 0x2d, 0xc7, 0x89, 0x5f, 0x46, 0x12, 0x74, 0xd8, 0x84, 0xc7, 0xc0, 0x98, 0x11, 0x72,
	0xf2, 0x21, 0x3b, 0xed, 0x34, 0xb6, 0x11, 0x06, 0x66, 0x6d, 0xc1, 0xd0, 0x4b, 0x2f, 0xc1, 0x8a,
	0x44, 0x50, 0xc0, 0x7e, 0xae, 0xa4, 0x14, 0xfa, 0xb1, 0xfa, 0xad, 0xfa, 0x31, 0x8a, 0x64, 0x92,
	0xa6, 0x7f, 0xe8, 0xed, 0xa7, 0xdf, 0xbf, 0xf7, 0x9e, 0x31, 0x24, 0x7b, 0xe4, 0x45, 0xa7, 0xd1,
	0x62, 0x0a, 0xbc, 0x36, 0xb2, 0xc7, 0xf9, 0x63, 0x00, 0xa4, 0x44, 0x4e, 0xa7, 0x10, 0x2a, 0xc1,
	0x82, 0x2c, 0x58, 0x92, 0x2a, 0x54, 0x82, 0x52, 0x88, 0xda, 0xba, 0x91, 0x2c, 0xcc, 0x82, 0x65,
	0x52, 0x79, 0x4c, 0xe7, 0x40, 0x84, 0xd2, 0x8c, 0x78, 0xca, 0x41, 0xca, 0x60, 0xd4, 0x69, 0xdc,
	0xe9, 0xba, 0x61, 0x91, 0x67, 0x8f, 0x4f, 0x97, 0xaf, 0xf5, 0xce, 0xb0, 0x61, 0x9f, 0x77, 0x98,
	0x7e, 0x81, 0x91, 0xb1, 0x62, 0x83, 0x07, 0xcb, 0x62, 0x4f, 0xc7, 0xc6, 0x8a, 0xab, 0x83, 0x3d,
	0x0a, 0x52, 0x6b, 0x36, 0x3a, 0x09, 0x6b, 0xad, 0x5d, 0x8b, 0xe9, 0xe4, 0x96, 0x8d, 0xfb, 0x16,
	0x87, 0xdd, 0x4c, 0xab, 0x1a, 0xe9, 0x5a, 0x12, 0xbf, 0xee, 0xf1, 0x49, 0xbf, 0x01, 0x28, 0xb3,
	0x69, 0xb0, 0x55, 0x16, 0x35, 0x83, 0x2c, 0x58, 0x8e, 0xab, 0x44, 0x99, 0x8b, 0x9e, 0xc8, 0xbf,
	0xc3, 0xb4, 0x44, 0x7e, 0x59, 0x37, 0xb2, 0x92, 0xb7, 0x07, 0x69, 0xec, 0xe9, 0xc8, 0xe0, 0xf9,
	0xc8, 0xfc, 0x27, 0x4c, 0x4a, 0xe4, 0x95, 0x34, 0x1d, 0xb6, 0x46, 0x3a, 0xcb, 0x16, 0x45, 0x6f,
	0x19, 0x56, 0x1e, 0xd3, 0xcf, 0x40, 0xf6, 0xc8, 0xfd, 0xa7, 0x99, 0xac, 0xa2, 0xc2, 0xd9, 0x1d,
	0x91, 0xff, 0x82, 0x59, 0x89, 0xfc, 0xbf, 0x32, 0xf6, 0xc3, 0x38, 0x83, 0x68, 0x8f, 0xdc, 0xb0,
	0x30, 0x23, 0xa7, 0xbc, 0x67, 0x56, 0x0f, 0x01, 0x44, 0x7f, 0x35, 0xb6, 0x34, 0x87, 0xc8, 0xd5,
	0xd0, 0xb8, 0x58, 0x37, 0x9d, 0xbd, 0x4f, 0xe7, 0xc5, 0xab, 0xe2, 0x7c, 0x40, 0x17, 0x40, 0xfe,
	0x49, 0x4b, 0x67, 0xc5, 0xcb, 0xa3, 0xd2, 0x4f, 0xc5, 0xd9, 0xfe, 0xf9, 0x80, 0x32, 0x20, 0xbf,
	0x85, 0xa0, 0x7e, 0x4e, 0x9a, 0x14, 0x67, 0xca, 0x57, 0x88, 0xaf, 0x3b, 0x51, 0x5b, 0xf9, 0x9e,
	0xb8, 0x80, 0xb8, 0x92, 0x0d, 0xde, 0xc9, 0xb7, 0x13, 0xce, 0x7d, 0x7f, 0x86, 0x37, 0x44, 0x77,
	0x5b, 0x1e, 0xfb, 0xdf, 0xe9, 0xc7, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x8a, 0x09, 0x40,
	0x67, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CronClient is the client API for Cron service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CronClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobListResponse, error)
	Get(ctx context.Context, in *JobNameRequest, opts ...grpc.CallOption) (*JobResponse, error)
	Add(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Response, error)
	Remove(ctx context.Context, in *JobNameRequest, opts ...grpc.CallOption) (*Response, error)
}

type cronClient struct {
	cc *grpc.ClientConn
}

func NewCronClient(cc *grpc.ClientConn) CronClient {
	return &cronClient{cc}
}

func (c *cronClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobListResponse, error) {
	out := new(JobListResponse)
	err := c.cc.Invoke(ctx, "/Cron/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) Get(ctx context.Context, in *JobNameRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/Cron/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) Add(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Cron/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) Update(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Cron/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) Remove(ctx context.Context, in *JobNameRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Cron/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronServer is the server API for Cron service.
type CronServer interface {
	List(context.Context, *Empty) (*JobListResponse, error)
	Get(context.Context, *JobNameRequest) (*JobResponse, error)
	Add(context.Context, *Job) (*Response, error)
	Update(context.Context, *Job) (*Response, error)
	Remove(context.Context, *JobNameRequest) (*Response, error)
}

// UnimplementedCronServer can be embedded to have forward compatible implementations.
type UnimplementedCronServer struct {
}

func (*UnimplementedCronServer) List(ctx context.Context, req *Empty) (*JobListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedCronServer) Get(ctx context.Context, req *JobNameRequest) (*JobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCronServer) Add(ctx context.Context, req *Job) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedCronServer) Update(ctx context.Context, req *Job) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedCronServer) Remove(ctx context.Context, req *JobNameRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}

func RegisterCronServer(s *grpc.Server, srv CronServer) {
	s.RegisterService(&_Cron_serviceDesc, srv)
}

func _Cron_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cron/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cron/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).Get(ctx, req.(*JobNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cron/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).Add(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cron/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).Update(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cron/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).Remove(ctx, req.(*JobNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cron_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Cron",
	HandlerType: (*CronServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Cron_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Cron_Get_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Cron_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Cron_Update_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Cron_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}
