// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Agent struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Agent) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type Monitor struct {
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Cpu                  float32  `protobuf:"fixed32,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               float32  `protobuf:"fixed32,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Threads              int32    `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Monitor) Reset()         { *m = Monitor{} }
func (m *Monitor) String() string { return proto.CompactTextString(m) }
func (*Monitor) ProtoMessage()    {}
func (*Monitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *Monitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Monitor.Unmarshal(m, b)
}
func (m *Monitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Monitor.Marshal(b, m, deterministic)
}
func (m *Monitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Monitor.Merge(m, src)
}
func (m *Monitor) XXX_Size() int {
	return xxx_messageInfo_Monitor.Size(m)
}
func (m *Monitor) XXX_DiscardUnknown() {
	xxx_messageInfo_Monitor.DiscardUnknown(m)
}

var xxx_messageInfo_Monitor proto.InternalMessageInfo

func (m *Monitor) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Monitor) GetCpu() float32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *Monitor) GetMemory() float32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Monitor) GetThreads() int32 {
	if m != nil {
		return m.Threads
	}
	return 0
}

type Exception struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Exception) Reset()         { *m = Exception{} }
func (m *Exception) String() string { return proto.CompactTextString(m) }
func (*Exception) ProtoMessage()    {}
func (*Exception) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{2}
}

func (m *Exception) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exception.Unmarshal(m, b)
}
func (m *Exception) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exception.Marshal(b, m, deterministic)
}
func (m *Exception) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exception.Merge(m, src)
}
func (m *Exception) XXX_Size() int {
	return xxx_messageInfo_Exception.Size(m)
}
func (m *Exception) XXX_DiscardUnknown() {
	xxx_messageInfo_Exception.DiscardUnknown(m)
}

var xxx_messageInfo_Exception proto.InternalMessageInfo

func (m *Exception) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Exception) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AppMonitor struct {
	App                  *App     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Monitor              *Monitor `protobuf:"bytes,2,opt,name=monitor,proto3" json:"monitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppMonitor) Reset()         { *m = AppMonitor{} }
func (m *AppMonitor) String() string { return proto.CompactTextString(m) }
func (*AppMonitor) ProtoMessage()    {}
func (*AppMonitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{3}
}

func (m *AppMonitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppMonitor.Unmarshal(m, b)
}
func (m *AppMonitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppMonitor.Marshal(b, m, deterministic)
}
func (m *AppMonitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppMonitor.Merge(m, src)
}
func (m *AppMonitor) XXX_Size() int {
	return xxx_messageInfo_AppMonitor.Size(m)
}
func (m *AppMonitor) XXX_DiscardUnknown() {
	xxx_messageInfo_AppMonitor.DiscardUnknown(m)
}

var xxx_messageInfo_AppMonitor proto.InternalMessageInfo

func (m *AppMonitor) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *AppMonitor) GetMonitor() *Monitor {
	if m != nil {
		return m.Monitor
	}
	return nil
}

type JobMonior struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Monitor              *Monitor `protobuf:"bytes,2,opt,name=monitor,proto3" json:"monitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobMonior) Reset()         { *m = JobMonior{} }
func (m *JobMonior) String() string { return proto.CompactTextString(m) }
func (*JobMonior) ProtoMessage()    {}
func (*JobMonior) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{4}
}

func (m *JobMonior) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobMonior.Unmarshal(m, b)
}
func (m *JobMonior) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobMonior.Marshal(b, m, deterministic)
}
func (m *JobMonior) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobMonior.Merge(m, src)
}
func (m *JobMonior) XXX_Size() int {
	return xxx_messageInfo_JobMonior.Size(m)
}
func (m *JobMonior) XXX_DiscardUnknown() {
	xxx_messageInfo_JobMonior.DiscardUnknown(m)
}

var xxx_messageInfo_JobMonior proto.InternalMessageInfo

func (m *JobMonior) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *JobMonior) GetMonitor() *Monitor {
	if m != nil {
		return m.Monitor
	}
	return nil
}

type AppException struct {
	App                  *App       `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Exception            *Exception `protobuf:"bytes,2,opt,name=exception,proto3" json:"exception,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppException) Reset()         { *m = AppException{} }
func (m *AppException) String() string { return proto.CompactTextString(m) }
func (*AppException) ProtoMessage()    {}
func (*AppException) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{5}
}

func (m *AppException) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppException.Unmarshal(m, b)
}
func (m *AppException) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppException.Marshal(b, m, deterministic)
}
func (m *AppException) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppException.Merge(m, src)
}
func (m *AppException) XXX_Size() int {
	return xxx_messageInfo_AppException.Size(m)
}
func (m *AppException) XXX_DiscardUnknown() {
	xxx_messageInfo_AppException.DiscardUnknown(m)
}

var xxx_messageInfo_AppException proto.InternalMessageInfo

func (m *AppException) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *AppException) GetException() *Exception {
	if m != nil {
		return m.Exception
	}
	return nil
}

type JobException struct {
	Job                  *Job       `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Exception            *Exception `protobuf:"bytes,2,opt,name=exception,proto3" json:"exception,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JobException) Reset()         { *m = JobException{} }
func (m *JobException) String() string { return proto.CompactTextString(m) }
func (*JobException) ProtoMessage()    {}
func (*JobException) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{6}
}

func (m *JobException) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobException.Unmarshal(m, b)
}
func (m *JobException) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobException.Marshal(b, m, deterministic)
}
func (m *JobException) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobException.Merge(m, src)
}
func (m *JobException) XXX_Size() int {
	return xxx_messageInfo_JobException.Size(m)
}
func (m *JobException) XXX_DiscardUnknown() {
	xxx_messageInfo_JobException.DiscardUnknown(m)
}

var xxx_messageInfo_JobException proto.InternalMessageInfo

func (m *JobException) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *JobException) GetException() *Exception {
	if m != nil {
		return m.Exception
	}
	return nil
}

func init() {
	proto.RegisterType((*Agent)(nil), "Agent")
	proto.RegisterType((*Monitor)(nil), "Monitor")
	proto.RegisterType((*Exception)(nil), "Exception")
	proto.RegisterType((*AppMonitor)(nil), "AppMonitor")
	proto.RegisterType((*JobMonior)(nil), "JobMonior")
	proto.RegisterType((*AppException)(nil), "AppException")
	proto.RegisterType((*JobException)(nil), "JobException")
}

func init() { proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705) }

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0xcb, 0xd3, 0x30,
	0x18, 0x75, 0xed, 0xda, 0xae, 0xcf, 0xa6, 0x8e, 0x5c, 0x8c, 0xb2, 0x1b, 0x47, 0x41, 0x18, 0x2a,
	0x41, 0xe6, 0x95, 0x97, 0x15, 0x44, 0x29, 0x0e, 0x24, 0x97, 0xde, 0x48, 0xb3, 0x85, 0xd9, 0x41,
	0x9b, 0x87, 0x26, 0x82, 0xfb, 0x61, 0xfe, 0x3f, 0x49, 0x9a, 0x7e, 0xf9, 0xbe, 0x2f, 0xec, 0xee,
	0xe4, 0x3c, 0xe7, 0x9c, 0x9e, 0x7c, 0x14, 0x56, 0x55, 0xa1, 0xb4, 0x68, 0x28, 0x36, 0x52, 0xcb,
	0x2d, 0xf0, 0x42, 0x09, 0x87, 0xe3, 0x02, 0xb1, 0x83, 0x57, 0xc9, 0x5b, 0x98, 0xbe, 0x85, 0x20,
	0xbb, 0x88, 0x5a, 0x93, 0x17, 0xe0, 0x95, 0x98, 0xcc, 0x76, 0xb3, 0x7d, 0xcc, 0xbc, 0x12, 0x09,
	0x81, 0x39, 0xca, 0x46, 0x27, 0x9e, 0x65, 0x2c, 0x4e, 0x7f, 0x42, 0x74, 0x94, 0x75, 0xa9, 0x65,
	0x43, 0xd6, 0xe0, 0x63, 0x79, 0xb6, 0xd3, 0x80, 0x19, 0x68, 0x98, 0x13, 0xfe, 0x4e, 0xfc, 0xdd,
	0x6c, 0xef, 0x31, 0x03, 0xc9, 0x06, 0xc2, 0x4a, 0x54, 0xb2, 0xb9, 0x25, 0x73, 0x4b, 0xba, 0x15,
	0x49, 0x20, 0xd2, 0xbf, 0x1a, 0x51, 0x9c, 0x55, 0x12, 0x58, 0x7f, 0xb7, 0x4c, 0x3f, 0x42, 0xfc,
	0xf9, 0xcf, 0x49, 0xa0, 0x2e, 0x65, 0x6d, 0x1a, 0xe8, 0x1b, 0x0a, 0xd7, 0xc9, 0x62, 0x63, 0xad,
	0x84, 0x52, 0xc5, 0x45, 0xb8, 0x62, 0xdd, 0x32, 0xfd, 0x0a, 0x90, 0x21, 0x76, 0xf5, 0x36, 0xe0,
	0x17, 0xd8, 0x6e, 0x67, 0x79, 0x98, 0xd3, 0x0c, 0x91, 0x19, 0x82, 0xa4, 0x10, 0x55, 0xad, 0xc4,
	0xfa, 0x97, 0x87, 0x05, 0x75, 0x16, 0xd6, 0x0d, 0xd2, 0x2f, 0x10, 0xe7, 0x92, 0x1b, 0xba, 0x0d,
	0xba, 0x4a, 0xde, 0x07, 0xe5, 0x92, 0x33, 0x43, 0xdc, 0x15, 0xf4, 0x1d, 0x56, 0x19, 0xe2, 0xb0,
	0xa1, 0xa7, 0x4a, 0xed, 0x21, 0x16, 0x9d, 0xc8, 0xa5, 0x01, 0xed, 0x6d, 0x6c, 0x18, 0x9a, 0xc4,
	0x5c, 0xf2, 0x49, 0xe2, 0xa3, 0xed, 0xee, 0x4e, 0x3c, 0xfc, 0xf5, 0x20, 0x3c, 0xda, 0x27, 0x43,
	0x5e, 0xc1, 0x82, 0x89, 0x4b, 0x69, 0x71, 0x48, 0xed, 0xab, 0xd8, 0xc6, 0x94, 0x09, 0x85, 0xb2,
	0x56, 0x22, 0x7d, 0x46, 0x5e, 0x43, 0x94, 0x21, 0x7e, 0x2b, 0x95, 0xee, 0xe7, 0x6b, 0xea, 0x98,
	0xa9, 0x2c, 0x97, 0xfc, 0x3f, 0x99, 0x63, 0x46, 0xb2, 0x77, 0xb0, 0x1e, 0x2e, 0x8c, 0x09, 0xf3,
	0xc0, 0xc8, 0x92, 0x0e, 0xd4, 0xf4, 0xdb, 0x6f, 0xe0, 0x65, 0x7f, 0x29, 0x4e, 0x0c, 0xb4, 0x67,
	0xa6, 0xda, 0xf7, 0x40, 0xc6, 0xe7, 0xee, 0xe4, 0xcf, 0xe9, 0x98, 0x7c, 0xe0, 0x18, 0x9f, 0x6b,
	0xef, 0x18, 0x93, 0x13, 0xc7, 0xa7, 0xe0, 0x87, 0xdf, 0xe0, 0x89, 0x87, 0xf6, 0x2f, 0xfa, 0xf0,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x8e, 0xce, 0xed, 0x77, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	Register(ctx context.Context, in *Agent, opts ...grpc.CallOption) (*Response, error)
	AppList(ctx context.Context, in *Agent, opts ...grpc.CallOption) (*AppListResponse, error)
	JobList(ctx context.Context, in *Agent, opts ...grpc.CallOption) (*JobListResponse, error)
	AppMonitorReport(ctx context.Context, in *AppMonitor, opts ...grpc.CallOption) (*Response, error)
	JobMoniorReport(ctx context.Context, in *JobMonior, opts ...grpc.CallOption) (*Response, error)
	AppExceptionReport(ctx context.Context, in *AppException, opts ...grpc.CallOption) (*Response, error)
	JobExceptionReport(ctx context.Context, in *JobException, opts ...grpc.CallOption) (*Response, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) Register(ctx context.Context, in *Agent, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) AppList(ctx context.Context, in *Agent, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	err := c.cc.Invoke(ctx, "/Master/AppList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) JobList(ctx context.Context, in *Agent, opts ...grpc.CallOption) (*JobListResponse, error) {
	out := new(JobListResponse)
	err := c.cc.Invoke(ctx, "/Master/JobList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) AppMonitorReport(ctx context.Context, in *AppMonitor, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/AppMonitorReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) JobMoniorReport(ctx context.Context, in *JobMonior, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/JobMoniorReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) AppExceptionReport(ctx context.Context, in *AppException, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/AppExceptionReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) JobExceptionReport(ctx context.Context, in *JobException, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/JobExceptionReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
type MasterServer interface {
	Register(context.Context, *Agent) (*Response, error)
	AppList(context.Context, *Agent) (*AppListResponse, error)
	JobList(context.Context, *Agent) (*JobListResponse, error)
	AppMonitorReport(context.Context, *AppMonitor) (*Response, error)
	JobMoniorReport(context.Context, *JobMonior) (*Response, error)
	AppExceptionReport(context.Context, *AppException) (*Response, error)
	JobExceptionReport(context.Context, *JobException) (*Response, error)
}

// UnimplementedMasterServer can be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (*UnimplementedMasterServer) Register(ctx context.Context, req *Agent) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedMasterServer) AppList(ctx context.Context, req *Agent) (*AppListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppList not implemented")
}
func (*UnimplementedMasterServer) JobList(ctx context.Context, req *Agent) (*JobListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobList not implemented")
}
func (*UnimplementedMasterServer) AppMonitorReport(ctx context.Context, req *AppMonitor) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppMonitorReport not implemented")
}
func (*UnimplementedMasterServer) JobMoniorReport(ctx context.Context, req *JobMonior) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobMoniorReport not implemented")
}
func (*UnimplementedMasterServer) AppExceptionReport(ctx context.Context, req *AppException) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppExceptionReport not implemented")
}
func (*UnimplementedMasterServer) JobExceptionReport(ctx context.Context, req *JobException) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobExceptionReport not implemented")
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Agent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Register(ctx, req.(*Agent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_AppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Agent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).AppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/AppList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).AppList(ctx, req.(*Agent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_JobList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Agent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).JobList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/JobList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).JobList(ctx, req.(*Agent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_AppMonitorReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppMonitor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).AppMonitorReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/AppMonitorReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).AppMonitorReport(ctx, req.(*AppMonitor))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_JobMoniorReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobMonior)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).JobMoniorReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/JobMoniorReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).JobMoniorReport(ctx, req.(*JobMonior))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_AppExceptionReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppException)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).AppExceptionReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/AppExceptionReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).AppExceptionReport(ctx, req.(*AppException))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_JobExceptionReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobException)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).JobExceptionReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/JobExceptionReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).JobExceptionReport(ctx, req.(*JobException))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Master_Register_Handler,
		},
		{
			MethodName: "AppList",
			Handler:    _Master_AppList_Handler,
		},
		{
			MethodName: "JobList",
			Handler:    _Master_JobList_Handler,
		},
		{
			MethodName: "AppMonitorReport",
			Handler:    _Master_AppMonitorReport_Handler,
		},
		{
			MethodName: "JobMoniorReport",
			Handler:    _Master_JobMoniorReport_Handler,
		},
		{
			MethodName: "AppExceptionReport",
			Handler:    _Master_AppExceptionReport_Handler,
		},
		{
			MethodName: "JobExceptionReport",
			Handler:    _Master_JobExceptionReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
