// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Monitor struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Cpu                  float32  `protobuf:"fixed32,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               float32  `protobuf:"fixed32,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Threads              int32    `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Monitor) Reset()         { *m = Monitor{} }
func (m *Monitor) String() string { return proto.CompactTextString(m) }
func (*Monitor) ProtoMessage()    {}
func (*Monitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *Monitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Monitor.Unmarshal(m, b)
}
func (m *Monitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Monitor.Marshal(b, m, deterministic)
}
func (m *Monitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Monitor.Merge(m, src)
}
func (m *Monitor) XXX_Size() int {
	return xxx_messageInfo_Monitor.Size(m)
}
func (m *Monitor) XXX_DiscardUnknown() {
	xxx_messageInfo_Monitor.DiscardUnknown(m)
}

var xxx_messageInfo_Monitor proto.InternalMessageInfo

func (m *Monitor) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Monitor) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Monitor) GetCpu() float32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *Monitor) GetMemory() float32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Monitor) GetThreads() int32 {
	if m != nil {
		return m.Threads
	}
	return 0
}

type Archive struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	BeginTime            int64    `protobuf:"varint,3,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime              int64    `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Signal               string   `protobuf:"bytes,6,opt,name=signal,proto3" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Archive) Reset()         { *m = Archive{} }
func (m *Archive) String() string { return proto.CompactTextString(m) }
func (*Archive) ProtoMessage()    {}
func (*Archive) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *Archive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Archive.Unmarshal(m, b)
}
func (m *Archive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Archive.Marshal(b, m, deterministic)
}
func (m *Archive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Archive.Merge(m, src)
}
func (m *Archive) XXX_Size() int {
	return xxx_messageInfo_Archive.Size(m)
}
func (m *Archive) XXX_DiscardUnknown() {
	xxx_messageInfo_Archive.DiscardUnknown(m)
}

var xxx_messageInfo_Archive proto.InternalMessageInfo

func (m *Archive) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Archive) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Archive) GetBeginTime() int64 {
	if m != nil {
		return m.BeginTime
	}
	return 0
}

func (m *Archive) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Archive) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Archive) GetSignal() string {
	if m != nil {
		return m.Signal
	}
	return ""
}

type AgentMonitor struct {
	Agent                *AgentInfo `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Monitor              *Monitor   `protobuf:"bytes,2,opt,name=monitor,proto3" json:"monitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AgentMonitor) Reset()         { *m = AgentMonitor{} }
func (m *AgentMonitor) String() string { return proto.CompactTextString(m) }
func (*AgentMonitor) ProtoMessage()    {}
func (*AgentMonitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{2}
}

func (m *AgentMonitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMonitor.Unmarshal(m, b)
}
func (m *AgentMonitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMonitor.Marshal(b, m, deterministic)
}
func (m *AgentMonitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMonitor.Merge(m, src)
}
func (m *AgentMonitor) XXX_Size() int {
	return xxx_messageInfo_AgentMonitor.Size(m)
}
func (m *AgentMonitor) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMonitor.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMonitor proto.InternalMessageInfo

func (m *AgentMonitor) GetAgent() *AgentInfo {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *AgentMonitor) GetMonitor() *Monitor {
	if m != nil {
		return m.Monitor
	}
	return nil
}

type AppMonitor struct {
	App                  *App     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Monitor              *Monitor `protobuf:"bytes,2,opt,name=monitor,proto3" json:"monitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppMonitor) Reset()         { *m = AppMonitor{} }
func (m *AppMonitor) String() string { return proto.CompactTextString(m) }
func (*AppMonitor) ProtoMessage()    {}
func (*AppMonitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{3}
}

func (m *AppMonitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppMonitor.Unmarshal(m, b)
}
func (m *AppMonitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppMonitor.Marshal(b, m, deterministic)
}
func (m *AppMonitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppMonitor.Merge(m, src)
}
func (m *AppMonitor) XXX_Size() int {
	return xxx_messageInfo_AppMonitor.Size(m)
}
func (m *AppMonitor) XXX_DiscardUnknown() {
	xxx_messageInfo_AppMonitor.DiscardUnknown(m)
}

var xxx_messageInfo_AppMonitor proto.InternalMessageInfo

func (m *AppMonitor) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *AppMonitor) GetMonitor() *Monitor {
	if m != nil {
		return m.Monitor
	}
	return nil
}

type JobMonior struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Monitor              *Monitor `protobuf:"bytes,2,opt,name=monitor,proto3" json:"monitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobMonior) Reset()         { *m = JobMonior{} }
func (m *JobMonior) String() string { return proto.CompactTextString(m) }
func (*JobMonior) ProtoMessage()    {}
func (*JobMonior) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{4}
}

func (m *JobMonior) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobMonior.Unmarshal(m, b)
}
func (m *JobMonior) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobMonior.Marshal(b, m, deterministic)
}
func (m *JobMonior) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobMonior.Merge(m, src)
}
func (m *JobMonior) XXX_Size() int {
	return xxx_messageInfo_JobMonior.Size(m)
}
func (m *JobMonior) XXX_DiscardUnknown() {
	xxx_messageInfo_JobMonior.DiscardUnknown(m)
}

var xxx_messageInfo_JobMonior proto.InternalMessageInfo

func (m *JobMonior) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *JobMonior) GetMonitor() *Monitor {
	if m != nil {
		return m.Monitor
	}
	return nil
}

type TimingMonior struct {
	Timing               *Timing  `protobuf:"bytes,1,opt,name=timing,proto3" json:"timing,omitempty"`
	Monitor              *Monitor `protobuf:"bytes,2,opt,name=monitor,proto3" json:"monitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimingMonior) Reset()         { *m = TimingMonior{} }
func (m *TimingMonior) String() string { return proto.CompactTextString(m) }
func (*TimingMonior) ProtoMessage()    {}
func (*TimingMonior) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{5}
}

func (m *TimingMonior) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimingMonior.Unmarshal(m, b)
}
func (m *TimingMonior) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimingMonior.Marshal(b, m, deterministic)
}
func (m *TimingMonior) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimingMonior.Merge(m, src)
}
func (m *TimingMonior) XXX_Size() int {
	return xxx_messageInfo_TimingMonior.Size(m)
}
func (m *TimingMonior) XXX_DiscardUnknown() {
	xxx_messageInfo_TimingMonior.DiscardUnknown(m)
}

var xxx_messageInfo_TimingMonior proto.InternalMessageInfo

func (m *TimingMonior) GetTiming() *Timing {
	if m != nil {
		return m.Timing
	}
	return nil
}

func (m *TimingMonior) GetMonitor() *Monitor {
	if m != nil {
		return m.Monitor
	}
	return nil
}

type AppArchive struct {
	App                  *App     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Archive              *Archive `protobuf:"bytes,2,opt,name=archive,proto3" json:"archive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppArchive) Reset()         { *m = AppArchive{} }
func (m *AppArchive) String() string { return proto.CompactTextString(m) }
func (*AppArchive) ProtoMessage()    {}
func (*AppArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{6}
}

func (m *AppArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppArchive.Unmarshal(m, b)
}
func (m *AppArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppArchive.Marshal(b, m, deterministic)
}
func (m *AppArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppArchive.Merge(m, src)
}
func (m *AppArchive) XXX_Size() int {
	return xxx_messageInfo_AppArchive.Size(m)
}
func (m *AppArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_AppArchive.DiscardUnknown(m)
}

var xxx_messageInfo_AppArchive proto.InternalMessageInfo

func (m *AppArchive) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *AppArchive) GetArchive() *Archive {
	if m != nil {
		return m.Archive
	}
	return nil
}

type JobArchive struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Archive              *Archive `protobuf:"bytes,2,opt,name=archive,proto3" json:"archive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobArchive) Reset()         { *m = JobArchive{} }
func (m *JobArchive) String() string { return proto.CompactTextString(m) }
func (*JobArchive) ProtoMessage()    {}
func (*JobArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{7}
}

func (m *JobArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobArchive.Unmarshal(m, b)
}
func (m *JobArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobArchive.Marshal(b, m, deterministic)
}
func (m *JobArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobArchive.Merge(m, src)
}
func (m *JobArchive) XXX_Size() int {
	return xxx_messageInfo_JobArchive.Size(m)
}
func (m *JobArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_JobArchive.DiscardUnknown(m)
}

var xxx_messageInfo_JobArchive proto.InternalMessageInfo

func (m *JobArchive) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *JobArchive) GetArchive() *Archive {
	if m != nil {
		return m.Archive
	}
	return nil
}

type TimingArchive struct {
	Timing               *Timing  `protobuf:"bytes,1,opt,name=timing,proto3" json:"timing,omitempty"`
	Archive              *Archive `protobuf:"bytes,2,opt,name=archive,proto3" json:"archive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimingArchive) Reset()         { *m = TimingArchive{} }
func (m *TimingArchive) String() string { return proto.CompactTextString(m) }
func (*TimingArchive) ProtoMessage()    {}
func (*TimingArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{8}
}

func (m *TimingArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimingArchive.Unmarshal(m, b)
}
func (m *TimingArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimingArchive.Marshal(b, m, deterministic)
}
func (m *TimingArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimingArchive.Merge(m, src)
}
func (m *TimingArchive) XXX_Size() int {
	return xxx_messageInfo_TimingArchive.Size(m)
}
func (m *TimingArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_TimingArchive.DiscardUnknown(m)
}

var xxx_messageInfo_TimingArchive proto.InternalMessageInfo

func (m *TimingArchive) GetTiming() *Timing {
	if m != nil {
		return m.Timing
	}
	return nil
}

func (m *TimingArchive) GetArchive() *Archive {
	if m != nil {
		return m.Archive
	}
	return nil
}

func init() {
	proto.RegisterType((*Monitor)(nil), "Monitor")
	proto.RegisterType((*Archive)(nil), "Archive")
	proto.RegisterType((*AgentMonitor)(nil), "AgentMonitor")
	proto.RegisterType((*AppMonitor)(nil), "AppMonitor")
	proto.RegisterType((*JobMonior)(nil), "JobMonior")
	proto.RegisterType((*TimingMonior)(nil), "TimingMonior")
	proto.RegisterType((*AppArchive)(nil), "AppArchive")
	proto.RegisterType((*JobArchive)(nil), "JobArchive")
	proto.RegisterType((*TimingArchive)(nil), "TimingArchive")
}

func init() { proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705) }

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xa5, 0x9b, 0x34, 0x69, 0xa6, 0x5d, 0xa8, 0xbc, 0x52, 0x15, 0x56, 0x42, 0x54, 0xe1, 0x52,
	0x10, 0x32, 0xab, 0xf2, 0x0b, 0xc2, 0x05, 0xa8, 0xd8, 0x8b, 0xe9, 0x89, 0x0b, 0x4a, 0x1a, 0x93,
	0xf5, 0x8a, 0xc4, 0x56, 0xe2, 0x22, 0x71, 0xe5, 0x5f, 0xf0, 0x6f, 0x51, 0xfc, 0x91, 0xc4, 0xda,
	0x85, 0x2d, 0xb7, 0x99, 0xf7, 0xde, 0x3c, 0x8f, 0x9d, 0xd7, 0xc2, 0xa2, 0xca, 0x5a, 0x49, 0x1b,
	0x2c, 0x1a, 0x2e, 0xf9, 0x25, 0xe4, 0x59, 0x4b, 0x4d, 0x1d, 0x65, 0x42, 0xd8, 0xf2, 0x96, 0xe7,
	0xa6, 0x5c, 0x48, 0x56, 0xb1, 0xba, 0x34, 0xdd, 0x3c, 0x2b, 0x69, 0x2d, 0x75, 0x93, 0xb4, 0x10,
	0x5e, 0xf3, 0x9a, 0x49, 0xde, 0x20, 0x04, 0xfe, 0xf1, 0xc8, 0x8a, 0x78, 0xb2, 0x9e, 0x6c, 0x22,
	0xa2, 0x6a, 0xb4, 0x04, 0x4f, 0xb0, 0x22, 0x3e, 0x5b, 0x4f, 0x36, 0x53, 0xd2, 0x95, 0x1d, 0x72,
	0x10, 0xc7, 0xd8, 0x5b, 0x4f, 0x36, 0x67, 0xa4, 0x2b, 0xd1, 0x0a, 0x82, 0x8a, 0x56, 0xbc, 0xf9,
	0x19, 0xfb, 0x0a, 0x34, 0x1d, 0x8a, 0x21, 0x94, 0x37, 0x0d, 0xcd, 0x8a, 0x36, 0x9e, 0xaa, 0x79,
	0xdb, 0x26, 0xbf, 0x27, 0x10, 0xa6, 0xcd, 0xe1, 0x86, 0xfd, 0xa0, 0x27, 0x9e, 0xfa, 0x0c, 0x20,
	0xa7, 0x25, 0xab, 0xbf, 0x4a, 0x56, 0x51, 0x75, 0xb8, 0x47, 0x22, 0x85, 0xec, 0x59, 0x45, 0xd1,
	0x53, 0x98, 0xd1, 0xba, 0xd0, 0xa4, 0xaf, 0xc8, 0x90, 0xd6, 0x85, 0xa2, 0x56, 0x10, 0xb4, 0x32,
	0x93, 0x47, 0xbb, 0x84, 0xe9, 0x14, 0xce, 0xca, 0x3a, 0xfb, 0x1e, 0x07, 0xea, 0x64, 0xd3, 0x25,
	0x7b, 0x58, 0xa4, 0xdd, 0xfb, 0xd8, 0x57, 0x59, 0xc3, 0x54, 0xbd, 0x97, 0x5a, 0x70, 0xbe, 0x05,
	0xac, 0xd8, 0x8f, 0xf5, 0x37, 0x4e, 0x34, 0x81, 0x12, 0x08, 0x2b, 0x2d, 0x56, 0x1b, 0xcf, 0xb7,
	0x33, 0x6c, 0x86, 0x89, 0x25, 0x92, 0x0f, 0x00, 0xa9, 0x10, 0xd6, 0x73, 0x05, 0x5e, 0x26, 0x84,
	0x71, 0xf4, 0x71, 0x2a, 0x04, 0xe9, 0x80, 0x93, 0x9c, 0xde, 0x43, 0xb4, 0xe3, 0x79, 0x07, 0x6b,
	0xa3, 0x5b, 0x9e, 0xf7, 0x46, 0x3b, 0x9e, 0x93, 0x0e, 0x38, 0xc9, 0xe8, 0x33, 0x2c, 0xf6, 0x2a,
	0x16, 0xc6, 0xeb, 0x39, 0x04, 0x3a, 0x26, 0xc6, 0x2e, 0xc4, 0x9a, 0x26, 0x06, 0xfe, 0x8f, 0x7b,
	0xda, 0x6f, 0xfb, 0x8f, 0x7b, 0x66, 0x5a, 0xd2, 0x3b, 0x99, 0x11, 0x62, 0x89, 0xce, 0x69, 0xc7,
	0xf3, 0x91, 0xd3, 0xdf, 0x2e, 0xfa, 0xa0, 0xd3, 0x1e, 0xce, 0xf5, 0x4d, 0xac, 0xd9, 0x29, 0x37,
	0x7d, 0xc8, 0x75, 0xfb, 0xcb, 0x87, 0xe0, 0x5a, 0xfd, 0x0c, 0xd1, 0x0b, 0x98, 0x11, 0x5a, 0x32,
	0x55, 0x8f, 0xf2, 0x71, 0x19, 0x61, 0x42, 0x5b, 0xc1, 0xeb, 0x96, 0x26, 0x8f, 0xd0, 0x4b, 0x08,
	0x53, 0x21, 0x3e, 0xb1, 0x56, 0x3a, 0x9a, 0x25, 0x36, 0xa8, 0x2b, 0xdd, 0xf1, 0xfc, 0x1e, 0xa9,
	0x41, 0x47, 0xd2, 0x37, 0x00, 0x7a, 0xf7, 0x3b, 0xea, 0x0b, 0x3c, 0x10, 0xa3, 0x81, 0x2b, 0x40,
	0xe3, 0x78, 0x13, 0x2a, 0x78, 0x23, 0xd1, 0x39, 0x1e, 0x83, 0xee, 0xe2, 0xaf, 0x61, 0x39, 0x44,
	0xd7, 0xe8, 0xe7, 0x78, 0x80, 0x5c, 0xf5, 0x2b, 0x78, 0xd2, 0xc7, 0xd3, 0x88, 0x01, 0xf7, 0x88,
	0xab, 0xbd, 0x02, 0x34, 0x4e, 0x60, 0xbf, 0xcb, 0x18, 0xbc, 0x6f, 0x17, 0xfb, 0x2d, 0x46, 0xbb,
	0x18, 0xe8, 0x8e, 0x7a, 0x88, 0x50, 0xaf, 0x1e, 0x20, 0x57, 0xbd, 0x85, 0x0b, 0x27, 0x26, 0x66,
	0xe0, 0x31, 0x76, 0x50, 0x67, 0xe6, 0xdd, 0xf4, 0x8b, 0xd7, 0x88, 0x43, 0x1e, 0xa8, 0xff, 0xd2,
	0xb7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x88, 0x2a, 0x38, 0x25, 0x98, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*Response, error)
	AppList(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*AppListResponse, error)
	JobList(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*JobListResponse, error)
	TimingList(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*TimingListResponse, error)
	AgentMonitorReport(ctx context.Context, in *AgentMonitor, opts ...grpc.CallOption) (*Response, error)
	AppMonitorReport(ctx context.Context, in *AppMonitor, opts ...grpc.CallOption) (*Response, error)
	JobMoniorReport(ctx context.Context, in *JobMonior, opts ...grpc.CallOption) (*Response, error)
	TimingMoniorReport(ctx context.Context, in *TimingMonior, opts ...grpc.CallOption) (*Response, error)
	AppArchiveReport(ctx context.Context, in *AppArchive, opts ...grpc.CallOption) (*Response, error)
	JobArchiveReport(ctx context.Context, in *JobArchive, opts ...grpc.CallOption) (*Response, error)
	TimingArchiveReport(ctx context.Context, in *TimingArchive, opts ...grpc.CallOption) (*Response, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) AppList(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	err := c.cc.Invoke(ctx, "/Master/AppList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) JobList(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*JobListResponse, error) {
	out := new(JobListResponse)
	err := c.cc.Invoke(ctx, "/Master/JobList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) TimingList(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*TimingListResponse, error) {
	out := new(TimingListResponse)
	err := c.cc.Invoke(ctx, "/Master/TimingList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) AgentMonitorReport(ctx context.Context, in *AgentMonitor, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/AgentMonitorReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) AppMonitorReport(ctx context.Context, in *AppMonitor, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/AppMonitorReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) JobMoniorReport(ctx context.Context, in *JobMonior, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/JobMoniorReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) TimingMoniorReport(ctx context.Context, in *TimingMonior, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/TimingMoniorReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) AppArchiveReport(ctx context.Context, in *AppArchive, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/AppArchiveReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) JobArchiveReport(ctx context.Context, in *JobArchive, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/JobArchiveReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) TimingArchiveReport(ctx context.Context, in *TimingArchive, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Master/TimingArchiveReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
type MasterServer interface {
	Register(context.Context, *AgentInfo) (*Response, error)
	AppList(context.Context, *AgentInfo) (*AppListResponse, error)
	JobList(context.Context, *AgentInfo) (*JobListResponse, error)
	TimingList(context.Context, *AgentInfo) (*TimingListResponse, error)
	AgentMonitorReport(context.Context, *AgentMonitor) (*Response, error)
	AppMonitorReport(context.Context, *AppMonitor) (*Response, error)
	JobMoniorReport(context.Context, *JobMonior) (*Response, error)
	TimingMoniorReport(context.Context, *TimingMonior) (*Response, error)
	AppArchiveReport(context.Context, *AppArchive) (*Response, error)
	JobArchiveReport(context.Context, *JobArchive) (*Response, error)
	TimingArchiveReport(context.Context, *TimingArchive) (*Response, error)
}

// UnimplementedMasterServer can be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (*UnimplementedMasterServer) Register(ctx context.Context, req *AgentInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedMasterServer) AppList(ctx context.Context, req *AgentInfo) (*AppListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppList not implemented")
}
func (*UnimplementedMasterServer) JobList(ctx context.Context, req *AgentInfo) (*JobListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobList not implemented")
}
func (*UnimplementedMasterServer) TimingList(ctx context.Context, req *AgentInfo) (*TimingListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimingList not implemented")
}
func (*UnimplementedMasterServer) AgentMonitorReport(ctx context.Context, req *AgentMonitor) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentMonitorReport not implemented")
}
func (*UnimplementedMasterServer) AppMonitorReport(ctx context.Context, req *AppMonitor) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppMonitorReport not implemented")
}
func (*UnimplementedMasterServer) JobMoniorReport(ctx context.Context, req *JobMonior) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobMoniorReport not implemented")
}
func (*UnimplementedMasterServer) TimingMoniorReport(ctx context.Context, req *TimingMonior) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimingMoniorReport not implemented")
}
func (*UnimplementedMasterServer) AppArchiveReport(ctx context.Context, req *AppArchive) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppArchiveReport not implemented")
}
func (*UnimplementedMasterServer) JobArchiveReport(ctx context.Context, req *JobArchive) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobArchiveReport not implemented")
}
func (*UnimplementedMasterServer) TimingArchiveReport(ctx context.Context, req *TimingArchive) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimingArchiveReport not implemented")
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Register(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_AppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).AppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/AppList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).AppList(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_JobList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).JobList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/JobList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).JobList(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_TimingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).TimingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/TimingList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).TimingList(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_AgentMonitorReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentMonitor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).AgentMonitorReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/AgentMonitorReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).AgentMonitorReport(ctx, req.(*AgentMonitor))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_AppMonitorReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppMonitor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).AppMonitorReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/AppMonitorReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).AppMonitorReport(ctx, req.(*AppMonitor))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_JobMoniorReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobMonior)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).JobMoniorReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/JobMoniorReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).JobMoniorReport(ctx, req.(*JobMonior))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_TimingMoniorReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimingMonior)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).TimingMoniorReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/TimingMoniorReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).TimingMoniorReport(ctx, req.(*TimingMonior))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_AppArchiveReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppArchive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).AppArchiveReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/AppArchiveReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).AppArchiveReport(ctx, req.(*AppArchive))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_JobArchiveReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobArchive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).JobArchiveReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/JobArchiveReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).JobArchiveReport(ctx, req.(*JobArchive))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_TimingArchiveReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimingArchive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).TimingArchiveReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Master/TimingArchiveReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).TimingArchiveReport(ctx, req.(*TimingArchive))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Master_Register_Handler,
		},
		{
			MethodName: "AppList",
			Handler:    _Master_AppList_Handler,
		},
		{
			MethodName: "JobList",
			Handler:    _Master_JobList_Handler,
		},
		{
			MethodName: "TimingList",
			Handler:    _Master_TimingList_Handler,
		},
		{
			MethodName: "AgentMonitorReport",
			Handler:    _Master_AgentMonitorReport_Handler,
		},
		{
			MethodName: "AppMonitorReport",
			Handler:    _Master_AppMonitorReport_Handler,
		},
		{
			MethodName: "JobMoniorReport",
			Handler:    _Master_JobMoniorReport_Handler,
		},
		{
			MethodName: "TimingMoniorReport",
			Handler:    _Master_TimingMoniorReport_Handler,
		},
		{
			MethodName: "AppArchiveReport",
			Handler:    _Master_AppArchiveReport_Handler,
		},
		{
			MethodName: "JobArchiveReport",
			Handler:    _Master_JobArchiveReport_Handler,
		},
		{
			MethodName: "TimingArchiveReport",
			Handler:    _Master_TimingArchiveReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
